/**
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates and open the template
 * in the editor.
 */
package MusicRetailManagement;

import javafx.scene.media.Media;
import javafx.scene.media.MediaPlayer;
import com.mpatric.mp3agic.ID3v1;
import com.mpatric.mp3agic.InvalidDataException;
import com.mpatric.mp3agic.Mp3File;
import com.mpatric.mp3agic.UnsupportedTagException;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.StandardCopyOption;
import java.sql.PreparedStatement;
import java.text.SimpleDateFormat;
import java.util.Date;

import java.util.logging.Level;
import java.util.logging.Logger;
import javafx.embed.swing.JFXPanel;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.UIManager;

/**
 * The Music Retail Management program implements an application that helps a
 * legal Music Retailer to sell music and keep accurate track of all songs
 * retailed
 *
 * @author Asante Kobby Emmanuel Annor
 * @id 47402017
 * @version 1.0
 *
 */
public class MusicRetailManagement extends javax.swing.JFrame {

    String fileName;
    String mp3Source;
    String mp3Destination;
    private static File sourceFile;
    private static File destinationFile;
    java.sql.Connection conn = null;
    private File files;
    String dbTitle;
    String dbArtist;
    String dbYear;
    String dbTimeSold;
    int dbSales = 1;

   

    /**
     * Creates new form MusicRetailManagement
     */
    public MusicRetailManagement() {
        JFXPanel fxPanel = new JFXPanel();
        initComponents();
        setTitle("Music Retail Management");

    }

    /**
     * This method previews a song a customer might want to purchase.
     *
     *
     * @throws FileNotFoundException
     */
    public void playTrack() throws FileNotFoundException {
        String bip = mp3Source;
        Media hit = new Media(new File(bip).toURI().toString());
        MediaPlayer mediaPlayer = new MediaPlayer(hit);
        mediaPlayer.play();

    }

    /**
     * This method initializes the database connection or connects the
     * application to the database to store accurate records of songs retailed
     * and their details
     *
     * @throws Exception
     */
    public void initialize() {
        try {
            Class.forName("com.mysql.jdbc.Driver").newInstance();
            conn = java.sql.DriverManager.getConnection(
                    "jdbc:mysql://localhost/musicretail?user=root&password=9144");

        } catch (Exception e) {
            System.out.println(e);
            System.exit(0);
        }
        System.out.println("Connection established");
    }

    /**
     * This method show alert messages containing information about the results
     * of an action.
     */
    public static void messageDisplay(String infoMessage, String titleBar) {
        JOptionPane.showMessageDialog(null, infoMessage, "messageBox: " + titleBar, JOptionPane.INFORMATION_MESSAGE);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jInternalFrame1 = new javax.swing.JInternalFrame();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        addSingleBtn = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel8 = new javax.swing.JPanel();
        cartItems = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        checkoutBtn = new javax.swing.JButton();
        artistLabel = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        singleSoldName = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButtonPreviewSong = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jButtonRecords = new javax.swing.JButton();
        jButtonReceipt = new javax.swing.JButton();
        jButtonExit = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        jInternalFrame1.setVisible(true);

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("    Music Retail Management 1.0");
        setBackground(null);
        setMaximumSize(new java.awt.Dimension(800, 900));
        setMinimumSize(new java.awt.Dimension(655, 600));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-32388, -32340, -1, -1));

        jPanel2.setBackground(new java.awt.Color(25, 65, 25));
        jPanel2.setForeground(new java.awt.Color(0, 153, 0));
        jPanel2.setToolTipText("");

        addSingleBtn.setFont(new java.awt.Font("Segoe UI Light", 1, 24)); // NOI18N
        addSingleBtn.setForeground(new java.awt.Color(0, 153, 0));
        addSingleBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Money Bag_48px.png"))); // NOI18N
        addSingleBtn.setText("Buy Song");
        addSingleBtn.setToolTipText("");
        addSingleBtn.setBorder(new javax.swing.border.MatteBorder(null));
        addSingleBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addSingleBtnActionPerformed(evt);
            }
        });

        jPanel6.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        jPanel6.setForeground(new java.awt.Color(0, 153, 0));

        jTabbedPane1.setForeground(new java.awt.Color(0, 153, 0));
        jTabbedPane1.setFont(new java.awt.Font("Segoe UI Light", 1, 12)); // NOI18N

        jPanel8.setForeground(new java.awt.Color(0, 153, 0));

        cartItems.setForeground(new java.awt.Color(0, 153, 0));
        cartItems.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        cartItems.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel17.setBackground(new java.awt.Color(0, 255, 255));
        jLabel17.setFont(new java.awt.Font("Segoe UI Light", 1, 24)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 153, 0));
        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Purchase Order_32px.png"))); // NOI18N
        jLabel17.setText("Song in Order");
        jLabel17.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        checkoutBtn.setFont(new java.awt.Font("Segoe UI Light", 1, 24)); // NOI18N
        checkoutBtn.setForeground(new java.awt.Color(0, 153, 0));
        checkoutBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Checkout_48px_1.png"))); // NOI18N
        checkoutBtn.setText("Checkout");
        checkoutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkoutBtnActionPerformed(evt);
            }
        });

        artistLabel.setForeground(new java.awt.Color(0, 153, 0));
        artistLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel5.setText("Song Details");

        jLabel6.setText("File Details");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 116, Short.MAX_VALUE))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(checkoutBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cartItems, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(artistLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel5))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cartItems, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(artistLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(checkoutBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Calculator", jPanel8);

        jLabel4.setFont(new java.awt.Font("Segoe UI Light", 1, 11)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 153, 0));
        jLabel4.setText("Date/Time Sold");

        jLabel7.setFont(new java.awt.Font("Segoe UI Light", 1, 11)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 153, 0));
        jLabel7.setText("Song Sold");

        singleSoldName.setForeground(new java.awt.Color(0, 153, 0));
        singleSoldName.setBorder(new javax.swing.border.MatteBorder(null));

        jLabel3.setForeground(new java.awt.Color(0, 153, 0));
        jLabel3.setBorder(new javax.swing.border.MatteBorder(null));

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(singleSoldName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel7))
                        .addGap(0, 245, Short.MAX_VALUE))))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(singleSoldName, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(155, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Receipt", jPanel9);

        jButtonPreviewSong.setText("Preview Selected Song");
        jButtonPreviewSong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPreviewSongActionPerformed(evt);
            }
        });

        jLabel9.setText("Music Preview Stops When You Click Any Button");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(46, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonPreviewSong, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonPreviewSong)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jLabel8.setBackground(new java.awt.Color(0, 153, 0));
        jLabel8.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Receive Cash_48px.png"))); // NOI18N
        jLabel8.setText("Price Per Song GHC1.5");
        jLabel8.setToolTipText("");

        jButtonRecords.setFont(new java.awt.Font("Segoe UI Light", 1, 24)); // NOI18N
        jButtonRecords.setForeground(new java.awt.Color(0, 153, 0));
        jButtonRecords.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Folder_48px.png"))); // NOI18N
        jButtonRecords.setText("Records");
        jButtonRecords.setToolTipText("");
        jButtonRecords.setBorder(new javax.swing.border.MatteBorder(null));
        jButtonRecords.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRecordsActionPerformed(evt);
            }
        });

        jButtonReceipt.setFont(new java.awt.Font("Segoe UI Light", 1, 24)); // NOI18N
        jButtonReceipt.setForeground(new java.awt.Color(0, 153, 0));
        jButtonReceipt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Receipt_48px.png"))); // NOI18N
        jButtonReceipt.setText("Receipt");
        jButtonReceipt.setToolTipText("");
        jButtonReceipt.setBorder(new javax.swing.border.MatteBorder(null));
        jButtonReceipt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonReceiptActionPerformed(evt);
            }
        });

        jButtonExit.setFont(new java.awt.Font("Segoe UI Light", 1, 24)); // NOI18N
        jButtonExit.setForeground(new java.awt.Color(0, 153, 0));
        jButtonExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Exit_48px.png"))); // NOI18N
        jButtonExit.setText("Exit");
        jButtonExit.setToolTipText("");
        jButtonExit.setBorder(new javax.swing.border.MatteBorder(null));
        jButtonExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonExit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonReceipt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(addSingleBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonRecords, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(addSingleBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonRecords, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonReceipt, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonExit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 690, 490));

        jPanel1.setBackground(new java.awt.Color(25, 75, 25));

        jLabel1.setBackground(new java.awt.Color(25, 75, 25));
        jLabel1.setFont(new java.awt.Font("Segoe UI Light", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Music Retail Management 1.0");
        jLabel1.setToolTipText("");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 584, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(96, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 690, 70));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * This method opens a dialog box to save the song purchased by the customer
     * to his or her device.
     *
     * @throws FileNotFoundException
     * @throws Exception
     */
    private void checkoutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkoutBtnActionPerformed
        int result = fc.showDialog(null, "Select Customer's Media to Complete Purchase Process");
        if (result == JFileChooser.APPROVE_OPTION) {
            fileName = fc.getSelectedFile().toString();
            mp3Destination = fc.getSelectedFile().toString();
            destinationFile = new File(mp3Destination);
            try {
                Files.copy(sourceFile.toPath(), destinationFile.toPath(), StandardCopyOption.REPLACE_EXISTING);
            } catch (IOException ex) {
                Logger.getLogger(MusicRetailManagement.class.getName()).log(Level.SEVERE, null, ex);
            }
            String nameOfSingleSold = fc.getSelectedFile().getName();
            singleSoldName.setText(nameOfSingleSold);
            SimpleDateFormat dateFormat = new SimpleDateFormat("EEEE, dd MMMM yyyy, hh:mm:ss.SSS a");
            String stringDate = dateFormat.format(new Date());
            jLabel3.setText(stringDate);
            initialize();
            System.out.println("DONE!!!");
            try {
                PreparedStatement p = conn.prepareStatement(
                        "Insert Into song set song_title=?, "
                        + "artist_Name=? ,release_Year =?,"
                        + "time_Sold =?,no_of_sales=? ON DUPLICATE KEY UPDATE no_of_sales=no_of_sales+1;");
                p.setString(1, dbTitle);
                p.setString(2, dbArtist);
                p.setString(3, dbYear);
                p.setString(4, stringDate);
                p.setInt(5, dbSales = 1);
                p.execute();
            } catch (Exception e) {
                System.out.println("Error" + e.toString());
                return;
            }

            try {
                PreparedStatement p = conn.prepareStatement(
                        "Insert Into songTracking set song_title=?, "
                        + "artist_Name=? ,release_Year =?,"
                        + "time_Sold =?,customer_Device =?");

                p.setString(1, dbTitle);
                p.setString(2, dbArtist);
                p.setString(3, dbYear);
                p.setString(4, stringDate);
                p.setString(5, destinationFile.toString());
                p.execute();
            } catch (Exception e) {
                System.out.println("Error" + e.toString());
                return;
            }
            messageDisplay(dbArtist + " - " + dbTitle + " successfully purchased!", "Alert");
        } else {
            messageDisplay("Purchase Process cancelled", "Alert");
        }
    }//GEN-LAST:event_checkoutBtnActionPerformed

    /**
     * This method closes the program
     *
     */
    private void jButtonExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButtonExitActionPerformed

    /**
     * This method opens the receipt of all songs sold showing up-to-the-minute
     * details of all songs sold.
     *
     */
    private void jButtonReceiptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonReceiptActionPerformed
        Receipt newReceipt = new Receipt(null, true);
        newReceipt.setVisible(true);
    }//GEN-LAST:event_jButtonReceiptActionPerformed
    /**
     * This method activates the Records JFrame which shows the top selling
     * songs
     *
     */
    private void jButtonRecordsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRecordsActionPerformed
        Records newRecords = new Records(null, true);
        newRecords.setVisible(true);
    }//GEN-LAST:event_jButtonRecordsActionPerformed

    /**
     * This method opens a dialog box to select a song a customer wants to
     * purchase.
     * @throw Exceptions
     *
     */
    private void addSingleBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addSingleBtnActionPerformed
        fc.setMultiSelectionEnabled(true);
        fc.setCurrentDirectory(new File(System.getProperty("user.home") + System.getProperty("file.separator") + "Music"));
        fc.setFileFilter(new FileTypeFilter(".mp3", "music File"));
        int result = fc.showDialog(null, "Select a song to Purchase");
        File[] files = fc.getSelectedFiles();
        if (result == JFileChooser.APPROVE_OPTION) {
            mp3Source = fc.getSelectedFile().toString();//readies the selected file to be copied
            sourceFile = new File(mp3Source);
            Mp3File mp3file = null;
            try {
                mp3file = new Mp3File(mp3Source);
            } catch (java.nio.file.AccessDeniedException e) {
                return;
            } catch (IOException ex) {
                Logger.getLogger(MusicRetailManagement.class.getName()).log(Level.SEVERE, null, ex);
            } catch (UnsupportedTagException ex) {
                Logger.getLogger(MusicRetailManagement.class.getName()).log(Level.SEVERE, null, ex);
            } catch (InvalidDataException ex) {
                Logger.getLogger(MusicRetailManagement.class.getName()).log(Level.SEVERE, null, ex);
            }
            if (mp3file.hasId3v1Tag()) {
                ID3v1 id3v1Tag = mp3file.getId3v1Tag();
                dbTitle = id3v1Tag.getTitle();
                dbArtist = id3v1Tag.getArtist();
                dbYear = id3v1Tag.getYear();
                //dbTimeSold= stringDate();
                //dbSales= no_of_sales();

                cartItems.setText("<html>Artist: " + dbArtist
                        + "<br>Title: " + dbTitle + "<br>Album: " + dbYear + "<html>");
                // System.out.println("Title: " + id3v1Tag.getTitle());
                // System.out.println(");
                //System.out.println("Year: " + id3v1Tag.getYear()+);
                //System.out.println("Genre: " + id3v1Tag.getGenre()+ + " (" + id3v1Tag.getGenreDescription() + ")");
                //System.out.println("Comment: " + id3v1Tag.getComment());
            }
            artistLabel.setText(fc.getSelectedFile().toString());

        } else {
            messageDisplay("Purchase Process cancelled", "Alert");
            fileName = "the file";
        }
    }//GEN-LAST:event_addSingleBtnActionPerformed

    /**
     * This method calls the playTrack() method, which previews a song a
     * customer might want to purchase.
     */
    private void jButtonPreviewSongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPreviewSongActionPerformed
        try {
            playTrack();
        } catch (FileNotFoundException ex) {
            Logger.getLogger(MusicRetailManagement.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonPreviewSongActionPerformed
    final JFileChooser fc = new JFileChooser();

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel");
                //UIManager.setLookAndFeel("com.jtattoo.plaf.acryl.NoireLookAndFeel");
                // UIManager.setLookAndFeel("com.jtattoo.plaf.smart.SmartLookAndFeel");
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MusicRetailManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MusicRetailManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MusicRetailManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MusicRetailManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RetailerLogin().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addSingleBtn;
    private javax.swing.JLabel artistLabel;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel cartItems;
    private javax.swing.JButton checkoutBtn;
    private javax.swing.JButton jButtonExit;
    private javax.swing.JButton jButtonPreviewSong;
    private javax.swing.JButton jButtonReceipt;
    private javax.swing.JButton jButtonRecords;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel singleSoldName;
    // End of variables declaration//GEN-END:variables

}
